# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wKylxudzx2ohCUI1tFCpY_y0LPuBtq-
"""

import pandas as pd

df = pd.read_csv('dados_nao_tratados.csv')

#converte uma coluna para numérico (int ou float)
df['idade'] = df['idade'].replace('vinte e três', 23)

#preenche todos os valores nulos com 0.
df.fillna(0, inplace=True)

#Converter a coluna 'nota' para numérico,
df['nota'] = pd.to_numeric(df['nota'], errors='coerce')

#Converter a coluna 'idade' para numérico,
df['idade'] = pd.to_numeric(df['idade'], errors='coerce')

#criar nova coluna
df['soma_dados'] = df['idade'] + df['nota']

#converte uma coluna Ativo
df['ativo'] = df['ativo'].astype(str).str.lower()
substituicoes = {
    'sim': 'sim',
    'true': 'Sim',
    'e': 'Sim',
    'Não': 'Sim',
    'não': 'Não'
}
df['ativo'] = df['ativo'].replace(substituicoes)

#Ajeitando o nome Èrica
df.loc[df['nome'] == 'Érica', 'nome'] = 'Erica'

# Ajeitar a data de inscrição para a "Erica e Carla"
df.loc[df['nome'] == 'Erica', 'data_inscricao'] = '2022-08-01'
df.loc[df['nome'] == 'Carla', 'data_inscricao'] = '2003-12-27'

#Colocando uma idade em Daniel
df.loc[df['nome'] == 'Daniel', 'idade'] = 24

print(df.head())