# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IdtHQLNXuAqk-mpfn6_ctVOJYBo2dro
"""

import numpy as np

# 1. Gerar as 7 temperaturas aleatórias (entre 20 e 35 graus)
Temperaturas = np.random.uniform(20, 35, 7)

# 2. Criar os dias da semana para a tabela
Dias_Semana = ['Domingo','Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado',]

print(Dias_Semana)
print (Temperaturas)

import pandas as pd

# 3. Criando o DataFrame com os dias e as temperaturas
data = {
    'Dia':['Domingo','Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado',],
    'Temperatura (°C)':[32, 28, 26, 20, 33, 26, 30]
}
df = pd.DataFrame(data)

# Imprimir o DataFrame
print("DataFrame da semana:")
print(df)
print(f"\nTemperatura média da semana: {mean_temperature:.2f}°C")

import matplotlib.pyplot as plt

days_of_the_week = ['Domingo','Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado',]
temperatures = [32, 28, 26, 20, 33, 26, 30]

plt.figure(figsize=(10, 6))
plt.plot(days_of_the_week, temperatures, marker='o', linestyle='-', color='b')
plt.title('Variação da Temperatura ao Longo da Semana', fontsize=16)
plt.xlabel('Dia da Semana', fontsize=12)
plt.ylabel('Temperatura (°C)', fontsize=12)

plt.grid(True)

plt.show()